[program:osonbot]
directory=/home/azureuser/osonbot
command=python3 app.py
autostart=true
autorestart=true
environment=HOME="/home/azureuser",USER="ubuntu"

strderr_logfile=/home/azureuser/osonbot/logfile_err.log
stdout_logfile=/home/azureuser/osonbot/logfile.log

