[program:bot]
directory=/home/ubuntu/osonbot
command=python3 app.py
autostart=true
autorestart=true
environment=HOME="/home/ubuntu", USER="ubuntu"

strderr_logfile=/home/ubuntu/osonbot/logfile_err.log
stdout_logfile=/home/ubuntu/osonbot/logfile.log

